spring:
  profiles:
    group:
      prod: prod

  application:
    name: radiant-app

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: 0.2
          max-tokens: 2048

  jpa:
    hibernate:
      ddl-auto: update

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
            scope:
              - read:user
              - user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - openid
              - profile
              - email

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 3600

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ink.radiant.query.model
  configuration:
    map-underscore-to-camel-case: true

radiant:
  translation:
    executor:
      core-pool-size: ${TRANSLATION_EXECUTOR_CORE_POOL_SIZE}
      max-pool-size: ${TRANSLATION_EXECUTOR_MAX_POOL_SIZE}
      queue-capacity: ${TRANSLATION_EXECUTOR_QUEUE_CAPACITY}
      keep-alive-seconds: ${TRANSLATION_EXECUTOR_KEEP_ALIVE_SECONDS}
      await-termination-seconds: ${TRANSLATION_EXECUTOR_AWAIT_TERMINATION_SECONDS}

  security:
    admin-tokens: ${RADIANT_ADMIN_TOKENS}
