spring:
  profiles:
    group:
      prod: prod

  application:
    name: radiant-app

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-or-v1-xxx}
      base-url: ${OPENAI_BASE_URL:https://openrouter.ai/api}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-4o-mini}
          temperature: 0.2
          max-tokens: 2048

  jpa:
    hibernate:
      ddl-auto: update

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:8080/api/auth/oauth2/callback/github}
            scope:
              - read:user
              - user:email
            authorization-grant-type: authorization_code
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/oauth2/callback/google}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 3600

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ink.radiant.query.model
  configuration:
    map-underscore-to-camel-case: true

radiant:
  translation:
    executor:
      core-pool-size: ${TRANSLATION_EXECUTOR_CORE_POOL_SIZE:4}
      max-pool-size: ${TRANSLATION_EXECUTOR_MAX_POOL_SIZE:8}
      queue-capacity: ${TRANSLATION_EXECUTOR_QUEUE_CAPACITY:100}
      keep-alive-seconds: ${TRANSLATION_EXECUTOR_KEEP_ALIVE_SECONDS:60}
      await-termination-seconds: ${TRANSLATION_EXECUTOR_AWAIT_TERMINATION_SECONDS:30}
  security:
    admin-tokens: ${RADIANT_ADMIN_TOKENS:test-admin-token}
